const samplePlatos = {
  'para-empezar': [
    { nombre: 'Empanadas mixtas (3)', descripcion: 'Empanadas de carne y pollo', precio: 8000 },
    { nombre: 'Patacones con hogao', descripcion: 'Patacones crujientes con salsa hogao', precio: 9000 },
    { nombre: 'Chicharrón tradicional', descripcion: 'Porción con yuca y limón', precio: 14000 },
    { nombre: 'Tequeños (4 unidades)', descripcion: 'Hilos de queso rebozados', precio: 7000 },
    { nombre: 'Arepitas con queso', descripcion: 'Arepitas pequeñas con queso costeño', precio: 6000 },
  ],
  sopas: [
    { nombre: 'Sopa de pollo', descripcion: 'Caldo con verduras y fideos', precio: 9000 },
    { nombre: 'Ajiaco bogotano', descripcion: 'Sopa tradicional con papa y pollo', precio: 18000 },
    { nombre: 'Sancocho de gallina', descripcion: 'Sancocho casero con yuca y plátano', precio: 16000 },
    { nombre: 'Crema de champiñones', descripcion: 'Suave crema con finas hierbas', precio: 12000 },
    { nombre: 'Sopa de lentejas', descripcion: 'Con tocino y verduras', precio: 10000 },
  ],
  carnes: [
    { nombre: 'Bistec a la criolla', descripcion: 'Bistec con cebolla y salsa criolla', precio: 25000 },
    { nombre: 'Costillas BBQ', descripcion: 'Costillas glaseadas con salsa casera', precio: 32000 },
    { nombre: 'Milanesa de res', descripcion: 'Milanesa empanada con papas', precio: 20000 },
    { nombre: 'Filete al ajillo', descripcion: 'Filete de res con ajo y mantequilla', precio: 30000 },
    { nombre: 'Cazuela de res', descripcion: 'Estofado tradicional', precio: 27000 },
  ],
  parrilla: [
    { nombre: 'Churrasco', descripcion: 'Corte jugoso a la parrilla', precio: 26000 },
    { nombre: 'Parrillada mixta', descripcion: 'Carnes y chorizos para compartir', precio: 35000 },
    { nombre: 'Pollo a la parrilla', descripcion: 'Pechuga marinada y asada', precio: 18000 },
    { nombre: 'Pincho de res', descripcion: 'Brocheta de carne con verduras', precio: 15000 },
    { nombre: 'Bife angosto', descripcion: 'Corte premium a la brasa', precio: 27000 },
  ],
  especiales: [
    { nombre: 'Pato confitado', descripcion: 'Pato lento con reducción de naranja', precio: 36000 },
    { nombre: 'Risotto de hongos', descripcion: 'Arroz cremoso con setas', precio: 28000 },
    { nombre: 'Filete en salsa de setas', descripcion: 'Filete con salsa cremosa', precio: 33000 },
    { nombre: 'Magret de pato', descripcion: 'Magret con guarnición especial', precio: 38000 },
    { nombre: 'Cazuela marinera', descripcion: 'Mariscos en salsa de tomate', precio: 34000 },
  ],
  ensaladas: [
    { nombre: 'Ensalada César', descripcion: 'Lechuga, croûtons y aderezo clásico', precio: 14000 },
    { nombre: 'Ensalada de quinoa', descripcion: 'Quinoa, vegetales y vinagreta', precio: 16000 },
    { nombre: 'Ensalada tropical', descripcion: 'Frutas y hojas frescas', precio: 15000 },
    { nombre: 'Ensalada de pollo', descripcion: 'Pollo asado sobre mix de lechugas', precio: 14000 },
    { nombre: 'Ensalada de aguacate', descripcion: 'Aguacate, tomate y aderezo de limón', precio: 17000 },
  ],
  hamburguesas: [
    { nombre: 'Hamburguesa clásica', descripcion: 'Carne, queso, lechuga y tomate', precio: 18000 },
    { nombre: 'Hamburguesa doble', descripcion: 'Doble carne y doble queso', precio: 25000 },
    { nombre: 'Hamburguesa vegetariana', descripcion: 'Hamburguesa de portobello y garbanzo', precio: 16000 },
    { nombre: 'Hamburguesa BBQ', descripcion: 'Con salsa BBQ y aros de cebolla', precio: 22000 },
    { nombre: 'Hamburguesa gourmet', descripcion: 'Ingredientes premium y pan artesanal', precio: 30000 },
  ],
  infantil: [
    { nombre: 'Mini hamburguesa', descripcion: 'Porción para niños', precio: 8000 },
    { nombre: 'Nuggets (6)', descripcion: 'Nuggets con papas', precio: 7000 },
    { nombre: 'Pasta con salsa roja', descripcion: 'Porción pequeña para niños', precio: 9000 },
    { nombre: 'Pizza mini', descripcion: 'Pizza pequeña con queso', precio: 10000 },
    { nombre: 'Pancakes con miel', descripcion: 'Tortitas dulces con miel', precio: 8000 },
  ],
  cafes: [
    { nombre: 'Café americano', descripcion: 'Taza grande', precio: 4000 },
    { nombre: 'Espresso', descripcion: 'Shot intenso de café', precio: 3500 },
    { nombre: 'Latte', descripcion: 'Café con leche espumada', precio: 6500 },
    { nombre: 'Cappuccino', descripcion: 'Espuma cremosa y cacao', precio: 6500 },
    { nombre: 'Mocha', descripcion: 'Café con chocolate y leche', precio: 7000 },
  ],
  jugos: [
    { nombre: 'Jugo natural', descripcion: 'Fruta del día', precio: 6000 },
    { nombre: 'Jugo mixto', descripcion: 'Mezcla de frutas frescas', precio: 7000 },
    { nombre: 'Limonada fresca', descripcion: 'Limonada natural', precio: 5000 },
    { nombre: 'Jugo de mango', descripcion: 'Mango natural', precio: 8000 },
    { nombre: 'Jugo de maracuyá', descripcion: 'Sabor tropical', precio: 8000 },
  ],
  bebidas: [
    { nombre: 'Gaseosa', descripcion: 'Botella 500ml', precio: 4000 },
    { nombre: 'Agua mineral', descripcion: 'Botella', precio: 3000 },
    { nombre: 'Té frío', descripcion: 'Té infusionado y frío', precio: 5000 },
    { nombre: 'Agua saborizada', descripcion: 'Con gas y sabor ligero', precio: 4500 },
    { nombre: 'Kombucha', descripcion: 'Bebida fermentada', precio: 12000 },
  ],
  licores: [
    { nombre: 'Cerveza local', descripcion: 'Botella 330ml', precio: 8000 },
    { nombre: 'Vino tinto (copa)', descripcion: 'Copa de vino', precio: 18000 },
    { nombre: 'Ron añejo (shot)', descripcion: 'Shot de ron', precio: 22000 },
    { nombre: 'Aguardiente (shot)', descripcion: 'Licor colombiano tradicional', precio: 15000 },
    { nombre: 'Cóctel de autor', descripcion: 'Trago de la casa', precio: 25000 },
  ],
};

export default samplePlatos;
